# Generated by Django 2.2.27 on 2022-03-18 21:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(max_length=100)),
                ('time_zone_offseet', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('lon', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('dt', models.DateTimeField()),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('forecast_type', models.CharField(choices=[('CUR', 'Currently Forecast'), ('MIN', 'Minute Forecast'), ('HOU', 'Hourly Forecast'), ('DAI', 'Daily Forecast')], default='CUR', max_length=3)),
            ],
        ),
    ]
