# Generated by Django 2.2.27 on 2022-03-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oraculum', '0002_auto_20220318_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherforecast',
            unique_together={('lat', 'lon', 'forecast_type')},
        ),
    ]
