# Generated by Django 2.2.27 on 2022-03-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculum', '0003_auto_20220318_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='dt',
            field=models.DateTimeField(null=True),
        ),
    ]
