# Generated by Django 2.2.27 on 2022-03-19 15:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(max_length=100)),
                ('time_zone_offset', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('lon', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('forecast_type', models.CharField(choices=[('CUR', 'Currently Forecast'), ('MIN', 'Minute Forecast'), ('HOU', 'Hourly Forecast'), ('DAI', 'Daily Forecast')], default='CUR', max_length=3)),
            ],
            options={
                'unique_together': {('lat', 'lon', 'forecast_type')},
            },
        ),
    ]
